/**
 * Guest Titles/Companies Mapping
 * Maps guest names to their episode focus/specialty
 */

export const GUEST_TITLES = {
  // Гости Подкаста Соколовского
  "Андрей Кривенко": "Основатель ВкусВилл",
  "Михаил Кучмент": "Сооснователь Hoff",
  "Борис Зарьков": "Ресторатор White Rabbit",
  "Иван Хохлов": "Сооснователь 12STOREEZ",
  "Олег Торбосов": "Основатель Whitewill",
  "Даниил и Давид Либерманы": "Инвесторы",
  "Фёдор Овчинников": "Основатель Додо Пиццы",
  "Игорь Рыбаков": "Сооснователь ТЕХНОНИКОЛЬ",
  "Леонид Гольдорт": "Основатель СДЭК",
  "Михаил Токовинин": "Основатель amoCRM",

  "Shreyas Doshi": "Product Leader & Coach",
  "Elena Verna": "Growth Advisor",
  "Ben Horowitz": "a16z Co-founder",
  "Brian Chesky": "Airbnb CEO",
  "Seth Godin": "Marketing Legend",
  "Brian Balfour": "Reforge Founder",
  "Eric Ries": "The Lean Startup Author",
  "Gibson Biddle": "Ex-Netflix VP Product",
  "Geoffrey Moore": "Crossing the Chasm Author",
  "Marty Cagan": "SVPG Partner",
  "Kim Scott": "Radical Candor Author",
  "Julie Zhuo": "The Making of a Manager",
  "Stewart Butterfield": "Slack Founder",
  "Dylan Field": "Figma CEO",
  "Tobi Lutke": "Shopify CEO",
  "Melanie Perkins": "Canva CEO",
  "Ivan Zhao": "Notion Founder",
  "Jason Fried": "37signals CEO",
  "Hamilton Helmer": "7 Powers Author",
  "Annie Duke": "Thinking in Bets Author",
  "Gokul Rajaram": "Pinterest/DoorDash Exec",
  "April Dunford": "Positioning Expert",
  "Patrick Campbell": "ProfitWell Founder",
  "Marc Benioff": "Salesforce CEO",
  "Drew Houston": "Dropbox CEO",
  "Ronny Kohavi": "A/B Testing Expert",
  "Casey Winters": "Eventbrite CPO",
  "Sean Ellis": "Growth Hacking Coiner",
  "Nir Eyal": "Hooked Author",
  "Ken Norton": "Ex-Google PM Partner",
  "Bill Carr": "Working Backwards Author",
  "Bret Taylor": "Salesforce Co-CEO",
  "Ryan Singer": "Shape Up Author",
  "Shishir Mehrotra": "Coda CEO",
  "Scott Belsky": "Adobe CPO",
  "Jessica Livingston": "Y Combinator Co-founder",
  "Nikita Bier": "Gas/TBH Founder",
  "Julian Shapiro": "Demand Curve Founder",
  "Karri Saarinen": "Linear Co-founder",
  "Matt Mullenweg": "WordPress Founder",
  "Yuhki Yamashata": "Figma CPO",
  "Peter Deng": "OpenAI/Airtable VP",
  "Naomi Gleit": "Meta Head of Product",
  "Mike Krieger": "Instagram Co-founder",
  "Boz": "Meta CTO",
  "Chip Huyen": "Claypot AI Founder",
  "Hamel Husain & Shreya Shankar": "AI Engineers",
  "Dr. Fei Fei Li": "AI Pioneer",
  "Nicole Forsgren": "DORA/DevOps Expert",
  "Gergely": "The Pragmatic Engineer",
  "David Singleton": "Stripe CTO",
  "Guillermo Rauch": "Vercel CEO",
  "Amjad Masad": "Replit CEO",
  "Howie Liu": "Airtable CEO",
  "Uri Levine": "Waze Co-founder",
  "Rahul Vohra": "Superhuman CEO",
  "Teresa Torres": "Continuous Discovery",
  "Melissa Perri": "Escaping the Build Trap",
  "Bob Moesta": "Jobs to Be Done",
  "Madhavan Ramanujam": "Monetizing Innovation",
  "Roger Martin": "Strategy Advisor",
  "Richard Rumelt": "Strategy Expert",
  "Jake Knapp + John Zeratsky": "Sprint Authors",
  "Janna Bastow": "ProdPad CEO",
  "Nancy Duarte": "Duarte Design CEO",
  "John Cutler": "Product Thought Leader",
  "Nikhyl Singhal": "Meta VP Product",
  "Itamar Gilad": "Evidence-Guided PM",
  "Ravi Mehta": "Outpace CEO",
  "Deb Liu": "Ancestry CEO",
  "Josh Miller": "The Browser Company CEO",
  "Sarah Tavel": "Benchmark Partner",
  "Mike Maples Jr": "Floodgate Partner",
  "Dalton Caldwell": "YC Group Partner",
  "Jason M Lemkin": "SaaStr Founder",
  "Kunal Shah": "CRED Founder",
  "Gustaf Alstromer": "YC Group Partner",
  "Andy Johns": "Growth Investor",
  "Bangaly Kaba": "Poparazzi/Instacart Growth",
  "Shaun Clowes": "MuleSoft CPO",
  "Andrew Wilkinson": "Tiny Capital Founder",
  "Wes Kao": "Maven Co-founder",
  "Kristen Berman": "Irrational Labs CEO",
  "Gia Laudi": "Forget the Funnel",
  "Emily Kramer": "MKT1 Co-founder",
  "Chip Conley": "Modern Elder Academy",
  "Oji Udezue": "Typeform CPO",
  "Claire Hughes Johnson": "Stripe Corporate Officer",
  "Molly Graham": "Scaling Expert",
  "Camille Fournier": "The Manager's Path",
  "Will Larson": "An Elegant Puzzle",
  "Matt Mochary": "CEO Coach",
  "Carole Robin": "Connect Author",
  "Jerry Colonna": "Reboot CEO",
  "Katie Dill": "Stripe Head of Design",
  "Brandon Chu": "Shopify VP Product",
  "Noah Weiss": "Slack CPO",
  "Kayvon Beykpour": "Ex-Twitter GM",
  "Todd Jackson": "First Round Capital",
  "Crystal W": "Reforge CPO",
  "Fareed Mosavat": "Reforge VP Growth",
  "Gina Gotthilf": "Duolingo Growth",
  "Garrett Lord": "Handshake CEO",
  "Petra Wille": "Strong Product People",
  "Jackie Bavaro": "Cracking the PM Interview",
  "Arielle Jackson": "Marketing Expert",
  "Adam Fishman": "Patreon/Lyft Growth",
  "Ami Vora": "Faire CPO",
  "Bob Baxley": "Ex-Apple Design",
  "Matthew Dicks": "Storyworthy Author",
  "Naomi Ionita": "Menlo Ventures Partner",
  "Gustav Söderström": "Spotify Co-President",
  "Eoghan McCabe": "Intercom CEO",
  "Logan Kilpatrick": "Google/OpenAI DevRel",
  "Scott Wu": "Cognition AI CEO",
  "Michael Truell": "Cursor AI CEO",
  "Sander Schulhoff": "Learn Prompting",
  "Dan Shipper": "Every Co-founder",
  "Varun Mohan": "Codeium CEO",
  "Anton Osika": "Lovable/GPT Engineer",
  "Alex Komoroske": "Stripe Principal PM",
  "Lulu Cheng Meservey": "Comms Exec",
  "Andy Raskin_": "Strategic Narrative",
  "Matt Abrahams": "Think Fast Talk Smart",
  "Christopher Lochhead": "Category Design",
  "David Placek": "Lexicon Branding CEO",
  "Tristan de Montebello": "Public Speaking Coach",
  "Jessica Hische": "Lettering Artist",
  "Donna Lichaw": "Story Mapping",
  "Paul Adams": "Intercom CPO",
  "Tomer Cohen": "LinkIn CPO",
  "Sam Lessin": "Slow Ventures",
  "Alisa Cohn": "Startup Coach",
  "Graham Weaver": "Alpine Investors CEO",
  "Jeffrey Pfeffer": "Stanford Professor",
  "Pete Kazanjy": "Founding Sales Author",
  "Sahil Mansuri": "Bravado CEO",
  "Matt Dixon": "The Challenger Sale",
  "Jason Shah": "Airbnb Product Lead",
  "Inbal S": "GitHub CPO",
  "Ramesh Johari": "Stanford Statistician",
  "Eli Schwartz": "SEO Expert",
  "Ryan Hoover": "Product Hunt Founder",
  "Chris Hutchins": "All The Hacks Host",
  "Hila Qu": "GitLab Growth",
  "Jules Walter": "YouTube Product Lead",
  "Julia Schottenstein": "NEA Partner",
  "Kevin Aluwi": "Gojek Co-founder",
  "Kevin Yien": "Square Head of Product",
  "Manik Gupta": "Microsoft CVP",
  "Mayur Kamat": "Binance Head of Product",
  "Ray Cao": "TikTok Managing Director",
  "Tamar Yehoshua": "Ex-Slack CPO",
  "Keith Coleman & Jay Baxter": "Twitter/Google Leaders",
  "Sriram and Aarthi": "The Good Time Show",
  "Upasna Gautam": "CNN Product Lead",
  "Varun Parmar": "Miro CPO",
  "Matt LeMay": "Product Coach",
  "Dmitry Zlokazov": "Product Leadership",
  "Ebi Atawodi": "Google Product Lead",
  "Edwin Chen": "Surge AI CEO",
  "Eeke de Milliano": "Stripe Product",
  "Emilie Gerber": "Sixfold Founder",
  "Evan LaPointe": "Product Strategy",
  "Gaurav Misra": "Captions CEO",
  "Geoff Charles": "Ramp VP Product",
  "Grant Lee": "Gamma Co-founder",
  "Heidi Helfand": "Dynamic Reteaming",
  "Hilary Gridley": "Product Leader",
  "Jackson Shuttleworth": "Product Strategy",
  "Jag Duggal": "Nubank CPO",
  "Jason Droege": "UberEverything Head",
  "Jeanne Grosser": "Stripe Head of Revenue",
  "Jeremy Henrickson": "Rippling CPO",
  "Jess Lachs": "DoorDash VP Analytics",
  "Jiaona Zhang": "Webflow CPO",
  "John Mark Nickels": "Uber Product",
  "Jonathan Becker": "Product Leader",
  "Jonathan Lowenhar": "Product Leader",
  "Karina Nguyen": "Product Management",
  "Keith Yandell": "DoorDash Product",
  "Kenneth Berger": "Slack Product",
  "Krithika Shankarraman": "Product Strategy",
  "Laura Modi": "Bobbie CEO",
  "Laura Schaffer": "Amplitude VP Product",
  "Lauren Ipsen": "Product Leadership",
  "Lauryn Isford": "Airtable Head of Growth",
  "Marily Nika": "AI Product Leader",
  "Matt MacInnis": "Rippling COO",
  "Maya Prohovnik": "Anchor Head of Product",
  "Megan Cook": "Atlassian Product",
  "Melissa Perri + Denise Tilles": "Product Operations",
  "Melissa Tan": "Webflow Head of Growth",
  "Meltem Kuran": "Deel Head of Growth",
  "Merci Grace": "Panther CEO",
  "Mihika Kapoor": "Product Management",
  "Nan Yu": "Linear CTO",
  "Nick Turley": "OpenAI Product",
  "Nickey Skarstad": "Duolingo VP Product",
  "Nilan Peiris": "Wise CPO",
  "Noam Lovinsky": "Grammarly CPO",
  "Paige Costello": "Asana Core Product",
  "Phyl Terry": "Slow Growth Founder",
  "Raaz Herzberg": "Wiz VP Product",
  "Rachel Lockett": "Product Management",
  "Robby Stein": "Instagram/Yahoo Product",
  "Ryan J. Salva": "GitHub VP Product",
  "Sachin Monga": "Cocoon Co-founder",
  "Sanchan Saxena": "Coinbase VP Product",
  "Shweta Shriva": "Product Leadership",
  "Sri Batchu": "Instacart/Opendoor Exec",
  "Tim Holley": "Etsy VP Product",
  "Timothy Davis": "Product Leadership",
  "Vijay": "Product Management",
  "Vikrama Dhiman": "Product Strategy",
  "Yuriy Timen": "Growth Advisor",
  "Zoelle Egner": "Product Management",
  "Tom Conrad": "Zero CEO / Pandora",
  "Kevin Weil": "Planet President",
  "Tanguy Crusson": "Atlassian Product",
  "Jeff Weinstein": "Stripe Product Lead",
  "Sam Schillace": "Microsoft Deputy CTO",
  "Lane Shackleton": "Coda CPO",
  "Christina Wodtke": "Radical Focus Author",
  "Nikita Miller": "The Knot CPO",
  "Camille Hearst": "Spotify Head of Fan",
  "Luc Levesque": "Shopify VP Growth",
  "Christopher Miller": "Product Leadership",
  "Jason Feifer": "Entrepreneur Mag Editor",
  "Paul Millerd": "The Pathless Path",
  "Jonny Miller": "Nervous System Mastery",
  "Joe Hudson": "Leadership Coach",
  "Dan Hockenmaier": "Faire Strategy Lead",
  "Ethan Evans": "Ex-Amazon VP",
  "Ian McAllister": "Amazon/Uber Product",
  "Dhanji R. Prasanna": "Tinder CTO",
  "Farhan Thawar": "Shopify VP Eng",
  "Hari Srinivasan": "Linkedin VP Product",
  "Maggie Crowley": "Toast/Drift Product",
  "Shreyas Doshi Live": "PM Masterclass",
  "Jen Abel": "JJELLYFISH Founder",
  "Alex Hardimen": "New York Times CPO",
  "Benjamin Lauzier": "Product/Growth Leader",
  "Benjamin Mann": "Anthropic Co-founder",
  "Carilu Dietrich": "Ex-Atlassian CMO",
  "Judd Antin": "Design/Research Leader",
  "Melissa": "Product Management",
  "Dharmesh Shah": "HubSpot Founder/CTO",
  "Nabeel S. Qureshi": "Palantir/Product",
  "Anneka Gupta": "Rubrik CPO",
  "Aparna Chennapragada": "Microsoft CVP",
  "Asha Sharma": "Instacart COO",
  "Ayo Omojola": "Carbon Health CPO",
  "Cam Adams": "Canva Co-founder",
  "Camille Ricketts": "Notion Marketing",
  "Chandra Janakiraman": "Salesforce Product",
  "Christian Idiodi": "SVPG Partner",
  "Christine Itwaru": "Pendo Product",
  "Claire Butler": "Figma Marketing",
  "Claire Vo": "LaunchDarkly CPO",
  "Daniel Lereya": "Monday.com CPO",
  "Elizabeth Stone": "Netflix CTO",
  "Eric Simons": "StackBlitz CEO",
  "Ethan Smith": "Graphite CEO",
  "Failure": "Learning Experience",
  "Ada Chen Rekhi": "Notejoy Founder",
  "Adam Grenier": "Uber/Lambda Growth",
  "Adriel Frederick": "Product Management",
  "Aishwarya Naresh Reganti + Kiriti Badam": "AI & Design",
  "Albert Cheng": "Amazon Prime Video",
  "Alexander Embiricos": "Remotion Founder",
  "Annie Pearl": "Calendly CPO",
  "Anuj Rathi": "Jupiter Money CPO",
  "Archie Abrams": "Udemy VP Product",
  "Austin Hay": "Ramp Head of MarTech",
  "Barbra Gago": "Pando CEO",
  "Ben Williams": "Snyk VP Product",
  "Brendan Foody": "Mercari US CEO",
  "Brian Tolkin": "Opendoor VP Product",
  "Zevi Arnovitz": "GitHub Product",
  "Interview Q Compilation": "PM Interview Prep",
  "EOY Review": "Year in Review",
  "Teaser_2021": "Preview Content",
  "default": "Гость подкаста"
};

export function getGuestTitle(guestName) {
  if (!guestName) return GUEST_TITLES.default;
  return GUEST_TITLES[guestName] || GUEST_TITLES.default;
}
